### ISSUE TITLE
MySQL 8 problem

### ISSUE THREAD

**Issue by uwegeercken** [uwegeercken/rule_maintenance_war#1]
Dan Keeley reported that MySQL 8 does not work. No connection is established, but no error message is available.

Verified and confirmed that "com.mysql.jdbc.Driver" is used.

**Comment by uwegeercken** [comment]
web app does work with MySQL 8 when using the appropriate driver for v8; confirmed by Dan.

**Comment by uwegeercken** [comment]
is not an issue.

**Comment by ekrishgit** [comment]
Hello Uwe,

I have the same issue. Tried to configure the MySql 8 Database but couldn't connect. I was able to make a client connection to MySql but not just from the application. MySql log shows Connection is aborted.
